import Foundation

/// The built-in formats, grouped by category. Names are English localization keys.
/// Adding a format or category is a data-only change here; tests guard uniqueness.
public enum FileTypeCatalog {
    public static let categories: [FileCategory] = [
        category("documents", "Documents", "doc.richtext", .blue, [
            ("doc", "Word 97–2004 Document"),
            ("docx", "Word Document"),
            ("docm", "Word Macro-Enabled Document"),
            ("dot", "Word 97–2004 Template"),
            ("dotx", "Word Template"),
            ("dotm", "Word Macro-Enabled Template"),
            ("odt", "OpenDocument Text"),
            ("ott", "OpenDocument Text Template"),
            ("fodt", "Flat OpenDocument Text"),
            ("rtf", "Rich Text Document"),
            ("rtfd", "Rich Text Document with Attachments"),
            ("pages", "Pages Document"),
            ("wpd", "WordPerfect Document"),
            ("wps", "Microsoft Works Document"),
            ("abw", "AbiWord Document"),
            ("hwp", "Hangul Word Document"),
            ("sxw", "StarOffice Writer Document"),
        ]),
        category("spreadsheets", "Spreadsheets", "tablecells", .green, [
            ("xls", "Excel 97–2004 Workbook"),
            ("xlsx", "Excel Workbook"),
            ("xlsm", "Excel Macro-Enabled Workbook"),
            ("xlsb", "Excel Binary Workbook"),
            ("xlt", "Excel 97–2004 Template"),
            ("xltx", "Excel Template"),
            ("xltm", "Excel Macro-Enabled Template"),
            ("ods", "OpenDocument Spreadsheet"),
            ("ots", "OpenDocument Spreadsheet Template"),
            ("fods", "Flat OpenDocument Spreadsheet"),
            ("numbers", "Numbers Spreadsheet"),
            ("csv", "Comma-Separated Values"),
            ("tsv", "Tab-Separated Values"),
            ("sxc", "StarOffice Calc Spreadsheet"),
        ]),
        category("presentations", "Presentations", "rectangle.on.rectangle.angled", .orange, [
            ("ppt", "PowerPoint 97–2004 Presentation"),
            ("pptx", "PowerPoint Presentation"),
            ("pptm", "PowerPoint Macro-Enabled Presentation"),
            ("pot", "PowerPoint 97–2004 Template"),
            ("potx", "PowerPoint Template"),
            ("potm", "PowerPoint Macro-Enabled Template"),
            ("pps", "PowerPoint 97–2004 Slide Show"),
            ("ppsx", "PowerPoint Slide Show"),
            ("ppsm", "PowerPoint Macro-Enabled Slide Show"),
            ("odp", "OpenDocument Presentation"),
            ("otp", "OpenDocument Presentation Template"),
            ("fodp", "Flat OpenDocument Presentation"),
            ("key", "Keynote Presentation"),
            ("sxi", "StarOffice Impress Presentation"),
        ]),
        category("books", "PDF & E-books", "book.closed", .red, [
            ("pdf", "PDF Document"),
            ("epub", "EPUB E-book"),
            ("mobi", "Mobipocket E-book"),
            ("azw", "Kindle E-book"),
            ("azw3", "Kindle KF8 E-book"),
            ("kfx", "Kindle KFX E-book"),
            ("fb2", "FictionBook E-book"),
            ("djvu", "DjVu Document"),
            ("xps", "XPS Document"),
            ("oxps", "OpenXPS Document"),
            ("cbz", "Comic Book Archive (ZIP)"),
            ("cbr", "Comic Book Archive (RAR)"),
            ("cb7", "Comic Book Archive (7z)"),
            ("chm", "Compiled HTML Help"),
            ("ibooks", "Apple Books Document"),
        ]),
        category("text", "Text & Markdown", "text.alignleft", .gray, [
            ("txt", "Plain Text"),
            ("md", "Markdown Document"),
            ("markdown", "Markdown Document"),
            ("mdx", "MDX Document"),
            ("rmd", "R Markdown Document"),
            ("qmd", "Quarto Document"),
            ("rst", "reStructuredText Document"),
            ("adoc", "AsciiDoc Document"),
            ("org", "Org Mode Document"),
            ("textile", "Textile Document"),
            ("tex", "LaTeX Document"),
            ("sty", "LaTeX Style"),
            ("cls", "LaTeX Class"),
            ("bib", "BibTeX Bibliography"),
            ("log", "Log File"),
            ("nfo", "Info File"),
        ]),
        category("web", "Web", "globe", .cyan, [
            ("html", "HTML Document"),
            ("htm", "HTML Document"),
            ("xhtml", "XHTML Document"),
            ("shtml", "Server-Side Include HTML"),
            ("mhtml", "MHTML Web Archive"),
            ("mht", "MHTML Web Archive"),
            ("webarchive", "Safari Web Archive"),
            ("css", "CSS Stylesheet"),
            ("scss", "Sass Stylesheet (SCSS)"),
            ("sass", "Sass Stylesheet"),
            ("less", "Less Stylesheet"),
            ("styl", "Stylus Stylesheet"),
            ("vue", "Vue Component"),
            ("svelte", "Svelte Component"),
            ("astro", "Astro Component"),
            ("hbs", "Handlebars Template"),
            ("ejs", "EJS Template"),
            ("pug", "Pug Template"),
            ("twig", "Twig Template"),
            ("erb", "ERB Template"),
            ("jsp", "JavaServer Page"),
            ("asp", "ASP Page"),
            ("aspx", "ASP.NET Page"),
        ]),
        category("code", "Source Code", "chevron.left.forwardslash.chevron.right", .indigo, [
            ("swift", "Swift Source"),
            ("m", "Objective-C Source"),
            ("mm", "Objective-C++ Source"),
            ("h", "C/C++ Header"),
            ("hpp", "C++ Header"),
            ("c", "C Source"),
            ("cpp", "C++ Source"),
            ("cc", "C++ Source"),
            ("cxx", "C++ Source"),
            ("cs", "C# Source"),
            ("fs", "F# Source"),
            ("vb", "Visual Basic Source"),
            ("java", "Java Source"),
            ("kt", "Kotlin Source"),
            ("kts", "Kotlin Script"),
            ("scala", "Scala Source"),
            ("groovy", "Groovy Source"),
            ("gradle", "Gradle Build Script"),
            ("clj", "Clojure Source"),
            ("go", "Go Source"),
            ("rs", "Rust Source"),
            ("zig", "Zig Source"),
            ("nim", "Nim Source"),
            ("js", "JavaScript"),
            ("mjs", "JavaScript Module"),
            ("cjs", "CommonJS Module"),
            ("jsx", "JavaScript JSX"),
            ("ts", "TypeScript / MPEG-2 Stream"),
            ("tsx", "TypeScript JSX"),
            ("cts", "TypeScript CommonJS Module"),
            ("coffee", "CoffeeScript"),
            ("dart", "Dart Source"),
            ("py", "Python Script"),
            ("pyi", "Python Stub"),
            ("ipynb", "Jupyter Notebook"),
            ("rb", "Ruby Script"),
            ("php", "PHP Script"),
            ("pl", "Perl Script"),
            ("pm", "Perl Module"),
            ("lua", "Lua Script"),
            ("r", "R Script"),
            ("jl", "Julia Source"),
            ("ex", "Elixir Source"),
            ("exs", "Elixir Script"),
            ("erl", "Erlang Source"),
            ("hs", "Haskell Source"),
            ("ml", "OCaml Source"),
            ("elm", "Elm Source"),
            ("sol", "Solidity Contract"),
            ("asm", "Assembly Source"),
            ("sh", "Shell Script"),
            ("bash", "Bash Script"),
            ("zsh", "Zsh Script"),
            ("fish", "Fish Script"),
            ("ps1", "PowerShell Script"),
            ("bat", "Windows Batch File"),
            ("cmd", "Windows Command Script"),
            ("command", "Terminal Command"),
            ("applescript", "AppleScript Source"),
            ("sql", "SQL Script"),
            ("mk", "Makefile"),
            ("cmake", "CMake Script"),
            ("diff", "Diff File"),
            ("patch", "Patch File"),
        ]),
        category("data", "Data & Config", "curlybraces", .teal, [
            ("json", "JSON Document"),
            ("jsonc", "JSON with Comments"),
            ("json5", "JSON5 Document"),
            ("jsonl", "JSON Lines"),
            ("ndjson", "Newline-Delimited JSON"),
            ("geojson", "GeoJSON Document"),
            ("yaml", "YAML Document"),
            ("yml", "YAML Document"),
            ("toml", "TOML Document"),
            ("xml", "XML Document"),
            ("xsd", "XML Schema"),
            ("xsl", "XSL Stylesheet"),
            ("xslt", "XSLT Stylesheet"),
            ("plist", "Property List"),
            ("ini", "INI Configuration"),
            ("cfg", "Configuration File"),
            ("conf", "Configuration File"),
            ("env", "Environment File"),
            ("properties", "Java Properties"),
            ("lock", "Lock File"),
            ("graphql", "GraphQL Schema"),
            ("gql", "GraphQL Query"),
            ("proto", "Protocol Buffers Schema"),
            ("tf", "Terraform Configuration"),
            ("tfvars", "Terraform Variables"),
            ("hcl", "HCL Configuration"),
            ("reg", "Windows Registry File"),
            ("pem", "PEM Certificate"),
            ("crt", "Certificate"),
            ("cer", "Certificate"),
        ]),
        category("images", "Images", "photo", .pink, [
            ("jpg", "JPEG Image"),
            ("jpeg", "JPEG Image"),
            ("png", "PNG Image"),
            ("gif", "GIF Image"),
            ("heic", "HEIC Image"),
            ("heif", "HEIF Image"),
            ("webp", "WebP Image"),
            ("avif", "AVIF Image"),
            ("jxl", "JPEG XL Image"),
            ("jp2", "JPEG 2000 Image"),
            ("tiff", "TIFF Image"),
            ("tif", "TIFF Image"),
            ("bmp", "Bitmap Image"),
            ("ico", "Windows Icon"),
            ("icns", "macOS Icon"),
            ("svg", "SVG Image"),
            ("svgz", "Compressed SVG Image"),
            ("tga", "Targa Image"),
            ("exr", "OpenEXR Image"),
            ("hdr", "HDR Image"),
            ("dds", "DirectDraw Surface"),
            ("dng", "Adobe DNG Raw Image"),
            ("cr2", "Canon Raw Image"),
            ("cr3", "Canon CR3 Raw Image"),
            ("nef", "Nikon Raw Image"),
            ("arw", "Sony Raw Image"),
            ("raf", "Fujifilm Raw Image"),
            ("orf", "Olympus Raw Image"),
            ("rw2", "Panasonic Raw Image"),
            ("pef", "Pentax Raw Image"),
            ("srw", "Samsung Raw Image"),
            ("raw", "Raw Image"),
        ]),
        category("design", "Design", "paintpalette", .purple, [
            ("psd", "Photoshop Document"),
            ("psb", "Photoshop Large Document"),
            ("ai", "Illustrator Artwork"),
            ("eps", "Encapsulated PostScript"),
            ("ps", "PostScript Document"),
            ("indd", "InDesign Document"),
            ("idml", "InDesign Markup Document"),
            ("sketch", "Sketch Document"),
            ("fig", "Figma File"),
            ("xd", "Adobe XD Document"),
            ("afdesign", "Affinity Designer Document"),
            ("afphoto", "Affinity Photo Document"),
            ("afpub", "Affinity Publisher Document"),
            ("xcf", "GIMP Image"),
            ("kra", "Krita Document"),
            ("pxd", "Pixelmator Pro Document"),
            ("pxm", "Pixelmator Document"),
            ("procreate", "Procreate Artwork"),
            ("cdr", "CorelDRAW Drawing"),
            ("odg", "OpenDocument Drawing"),
            ("vsdx", "Visio Drawing"),
            ("drawio", "draw.io Diagram"),
            ("excalidraw", "Excalidraw Drawing"),
            ("graffle", "OmniGraffle Document"),
        ]),
        category("audio", "Audio", "waveform", .yellow, [
            ("mp3", "MP3 Audio"),
            ("m4a", "MPEG-4 Audio"),
            ("m4b", "Audiobook"),
            ("m4r", "iPhone Ringtone"),
            ("aac", "AAC Audio"),
            ("wav", "WAVE Audio"),
            ("aif", "AIFF Audio"),
            ("aiff", "AIFF Audio"),
            ("aifc", "AIFF-C Audio"),
            ("caf", "Core Audio File"),
            ("flac", "FLAC Audio"),
            ("ogg", "Ogg Vorbis Audio"),
            ("oga", "Ogg Audio"),
            ("opus", "Opus Audio"),
            ("wma", "Windows Media Audio"),
            ("ape", "Monkey's Audio"),
            ("wv", "WavPack Audio"),
            ("dsf", "DSD Audio (DSF)"),
            ("dff", "DSD Audio (DFF)"),
            ("mid", "MIDI Sequence"),
            ("midi", "MIDI Sequence"),
            ("amr", "AMR Audio"),
            ("ac3", "Dolby Digital Audio"),
            ("dts", "DTS Audio"),
            ("mka", "Matroska Audio"),
            ("m3u", "M3U Playlist"),
            ("m3u8", "M3U8 Playlist"),
            ("pls", "PLS Playlist"),
            ("cue", "Cue Sheet"),
        ]),
        category("video", "Video & Subtitles", "film", .mint, [
            ("mp4", "MPEG-4 Video"),
            ("m4v", "MPEG-4 Video (Apple)"),
            ("mov", "QuickTime Movie"),
            ("mkv", "Matroska Video"),
            ("webm", "WebM Video"),
            ("avi", "AVI Video"),
            ("wmv", "Windows Media Video"),
            ("flv", "Flash Video"),
            ("f4v", "Flash MP4 Video"),
            ("mpg", "MPEG Video"),
            ("mpeg", "MPEG Video"),
            ("m2v", "MPEG-2 Video"),
            ("vob", "DVD Video Object"),
            ("3gp", "3GPP Video"),
            ("3g2", "3GPP2 Video"),
            ("mts", "AVCHD Video"),
            ("m2ts", "Blu-ray Video"),
            ("ogv", "Ogg Video"),
            ("rm", "RealMedia Video"),
            ("rmvb", "RealMedia Variable Bitrate Video"),
            ("asf", "Advanced Systems Format Video"),
            ("divx", "DivX Video"),
            ("dv", "DV Video"),
            ("mxf", "MXF Video"),
            ("srt", "SubRip Subtitles"),
            ("vtt", "WebVTT Subtitles"),
            ("ass", "Advanced SubStation Subtitles"),
            ("ssa", "SubStation Alpha Subtitles"),
            ("sub", "Subtitles"),
            ("idx", "VobSub Subtitle Index"),
        ]),
        category("archives", "Archives & Disk Images", "archivebox", .brown, [
            ("zip", "ZIP Archive"),
            ("rar", "RAR Archive"),
            ("7z", "7-Zip Archive"),
            ("tar", "Tar Archive"),
            ("gz", "Gzip Archive"),
            ("tgz", "Gzipped Tar Archive"),
            ("bz2", "Bzip2 Archive"),
            ("tbz2", "Bzip2 Tar Archive"),
            ("xz", "XZ Archive"),
            ("txz", "XZ Tar Archive"),
            ("zst", "Zstandard Archive"),
            ("lz", "Lzip Archive"),
            ("lzma", "LZMA Archive"),
            ("lz4", "LZ4 Archive"),
            ("z", "Unix Compressed Archive"),
            ("cab", "Windows Cabinet Archive"),
            ("arj", "ARJ Archive"),
            ("lzh", "LZH Archive"),
            ("cpio", "CPIO Archive"),
            ("sit", "StuffIt Archive"),
            ("sitx", "StuffIt X Archive"),
            ("xar", "XAR Archive"),
            ("jar", "Java Archive"),
            ("war", "Web Application Archive"),
            ("apk", "Android Package"),
            ("ipa", "iOS App Archive"),
            ("deb", "Debian Package"),
            ("rpm", "RPM Package"),
            ("dmg", "Disk Image"),
            ("iso", "ISO Disk Image"),
            ("img", "Raw Disk Image"),
            ("sparseimage", "Sparse Disk Image"),
            ("toast", "Toast Disk Image"),
            ("pkg", "Installer Package"),
            ("xip", "Signed XIP Archive"),
        ]),
        category("fonts", "Fonts", "textformat", .indigo, [
            ("ttf", "TrueType Font"),
            ("otf", "OpenType Font"),
            ("ttc", "TrueType Font Collection"),
            ("otc", "OpenType Font Collection"),
            ("woff", "Web Font (WOFF)"),
            ("woff2", "Web Font (WOFF2)"),
            ("dfont", "Mac Data Fork Font"),
            ("pfb", "PostScript Type 1 Font"),
        ]),
        category("models3d", "3D & CAD", "cube", .orange, [
            ("stl", "STL 3D Model"),
            ("obj", "Wavefront OBJ Model"),
            ("fbx", "FBX 3D Model"),
            ("gltf", "glTF 3D Model"),
            ("glb", "glTF Binary Model"),
            ("usdz", "USDZ 3D Model"),
            ("usd", "USD Scene"),
            ("usda", "USD ASCII Scene"),
            ("usdc", "USD Crate Scene"),
            ("dae", "COLLADA Model"),
            ("3ds", "3DS Model"),
            ("max", "3ds Max Scene"),
            ("blend", "Blender Project"),
            ("c4d", "Cinema 4D Project"),
            ("ma", "Maya ASCII Scene"),
            ("mb", "Maya Binary Scene"),
            ("ply", "PLY 3D Model"),
            ("3mf", "3D Manufacturing Format"),
            ("step", "STEP CAD Model"),
            ("stp", "STEP CAD Model"),
            ("iges", "IGES CAD Model"),
            ("igs", "IGES CAD Model"),
            ("dwg", "AutoCAD Drawing"),
            ("dxf", "AutoCAD DXF Drawing"),
            ("skp", "SketchUp Model"),
            ("f3d", "Fusion 360 Design"),
            ("scad", "OpenSCAD Model"),
            ("gcode", "G-code Toolpath"),
        ]),
        category("communication", "Email & Internet", "envelope", .blue, [
            ("eml", "Email Message"),
            ("emlx", "Apple Mail Message"),
            ("msg", "Outlook Message"),
            ("oft", "Outlook Template"),
            ("mbox", "Mailbox"),
            ("pst", "Outlook Data File"),
            ("olm", "Outlook for Mac Archive"),
            ("vcf", "vCard Contact"),
            ("vcard", "vCard Contact"),
            ("ics", "Calendar Event"),
            ("torrent", "BitTorrent File"),
        ]),
        category("databases", "Databases", "cylinder.split.1x2", .green, [
            ("sqlite", "SQLite Database"),
            ("sqlite3", "SQLite Database"),
            ("db", "Database File"),
            ("mdb", "Access Database"),
            ("accdb", "Access Database"),
            ("dbf", "dBASE Table"),
            ("realm", "Realm Database"),
            ("duckdb", "DuckDB Database"),
            ("parquet", "Apache Parquet File"),
            ("avro", "Apache Avro File"),
            ("h5", "HDF5 Data File"),
        ]),
    ]

    private static func category(
        _ id: String,
        _ name: String,
        _ symbol: String,
        _ tint: CategoryTint,
        _ formats: [(ext: String, name: String)]
    ) -> FileCategory {
        FileCategory(
            id: id,
            name: name,
            symbol: symbol,
            tint: tint,
            formats: formats.map { FileFormat(ext: FileExtension($0.ext)!, name: $0.name, categoryID: id) }
        )
    }
}
